
name: 'steering-election'
on:
  workflow_dispatch:
    inputs:
      candidate:
          description: "Name of the candidate"
          required: true
  schedule:
    - cron: '*/10 * * * *' # checks for votes updates every 30 minutes

permissions: write-all

jobs:
  # start-voting:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'workflow_dispatch'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Start Vote
  #       uses: tfadeyi/start-vote@v0.1.0
  #       with:
  #         duration: 10m
  #         title: "Add ${{ github.event.inputs.candidate }} to steering committee"
  #         proposal: "Add ${{ github.event.inputs.candidate }} to steering committee"
  #         participants: "@tfadeyi,@tfadeyi1"
  #         yes: "${{ github.event.inputs.candidate }}"
  #         owner: "tfadeyi"
  #         repository: "oss-governance-test"
  #         voting: "simple_majority"
  #         category: "General"
  #         instance: "steering-election"
  monitor:
    outputs:
      outcome: ${{ steps.monitor.outputs.outcome }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Monitor Voting
        id: monitor
        uses: tfadeyi/get-voting-outcome@v0.1.7
        with:
          owner: "tfadeyi"
          repository: "tfadeyi/oss-governance-test"
          voting: simple_majority
          duration: 5m
          participants: "tfadeyi"
          labels: "steering-election"
          instance: "election"
  get-votes:
    runs-on: ubuntu-latest
    needs: monitor
    steps:
      - uses: actions/checkout@v4
      - env:
          OUTPUT1: ${{needs.monitor.outputs.outcome}}
        run: echo "$OUTOUT1" | jq -r .[].proposal | grep -o "@.*" >> ${{ env.home}}/steering
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update steering group"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
