
name: 'steering-election'
on:
  workflow_dispatch:
    inputs:
      candidate:
          description: "Name of the candidate"
          required: true
  schedule:
    - cron: '*/10 * * * *' # checks for votes updates every 30 minutes

permissions:
  issues: write
  repository-projects: write

jobs:
  # start-voting:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'workflow_dispatch'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Start Vote
  #       uses: tfadeyi/start-vote@v0.1.0
  #       with:
  #         duration: 10m
  #         title: "Add ${{ github.event.inputs.candidate }} to steering committee"
  #         proposal: "Add ${{ github.event.inputs.candidate }} to steering committee"
  #         participants: "@tfadeyi,@tfadeyi1"
  #         yes: "${{ github.event.inputs.candidate }}"
  #         owner: "tfadeyi"
  #         repository: "oss-governance-test"
  #         voting: "simple_majority"
  #         category: "General"
  #         instance: "steering-election"
  get-voting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Monitor Voting
        uses: tfadeyi/get-voting-outcome@v0.1.6
        with:
          owner: "tfadeyi"
          repository: "tfadeyi/oss-governance-test"
          voting: simple_majority
          duration: 5m
          participants: "tfadeyi"
          labels: "steering-election"
          instance: "election"
